### ISSUE TITLE
Wrong sentiment

### ISSUE THREAD

**Issue by misskbar** [cyhex/streamcrab#13]
Classify: today is good

Classification: negative with 64.81%

  Feature                                          negativ positiv

---

  today==1 (1)                                       0.325
  good==1 (1)                                       -0.044
  today==1 (1)                                              -0.631
  good==1 (1)                                                0.031

---

  TOTAL:                                             0.281  -0.600
  PROBS:                                             0.648   0.352

**Comment by cyhex** [comment]
This is something that is very depended on your training set and not on the code - see https://github.com/cyhex/streamcrab/blob/master/docs/acurracy_tests.md for optimum training set configurations. Besides that we are dealing with statistical analysis, therefore testing one random sentence is not  an correct indicator of engine performance
