### ISSUE TITLE
pool.py 

### ISSUE THREAD

**Issue by misskbar** [cyhex/streamcrab#14]
Line 50

49        row = TrainedClassifiers.objects(name=config.classifier).first()
50                    self.trained_classifier = row.get_classifier()

the element row is not recognize as a TrainedClassifiers therefore you can't do the get_classifier() method

Thank you

**Comment by cyhex** [comment]
local config problem

**Comment by ilnurmanapov** [comment]
cyhex, how to solve this problem?

**Comment by cyhex** [comment]
make sure to set an existing classifier name in config.ini 
classifier="some_classifier_name" make sure that it actually exists
