### ISSUE TITLE
other language

### ISSUE THREAD

**Issue by ilnurmanapov** [cyhex/streamcrab#15]
Timor, how to add russian language in setting for analysis of the russian tweets?

**Comment by cyhex** [comment]
streamcrab was develop for English only. However you can adjust to use Russian (or any other language)  by implementing the smm.classifier.textprocessing.TwitterProcessor using Russian stemmer and Russian stopwords.

You would also need to an adjust smm.datastream.plugins.twitterworker.TwitterWorker and null.TwitterCollector to filter for Russian language.

Hope it helps, if you do succeed please contribute back :)
