### ISSUE TITLE
Classifier NoneType Error

### ISSUE THREAD

**Issue by ilkaytaskiran** [cyhex/streamcrab#16]
Hi

python start-classifier.py running . 

After error give program

Traceback (most recent call last):
  File "start-classifier.py", line 14, in <module>
    pool = ClassifierWorkerPool()
  File "/home/ilkay/Masaüstü/streamcrab-master/smm/classifier/pool.py", line 50, in **init**
    self.trained_classifier = row.get_classifier()
AttributeError: 'NoneType' object has no attribute 'get_classifier'

What should I do ?

Thanks

**Comment by cyhex** [comment]
You are trying not get a non existing classifier. Change the name of the classifier in config.py to one that exists.

**Comment by cyhex** [comment]
In config.ini see also issue #14
fixed in 7736dea

**Comment by ilkaytaskiran** [comment]
Thank you,

But python toolbox/train-classifier.py MyDataClasses 2000
There is only 276 positive tweeets in DB

config.py  (classifier): MyDataClasses

python shell-classifier.py MyDataClasses
TrainedClassifier MyDataClasses do not exists

python start-classifier.pyTraceback (most recent call last):
  File "start-classifier.py", line 14, in <module>
    pool = ClassifierWorkerPool()
  File "/home/ilkay/streamcrab/smm/classifier/pool.py", line 50, in **init**
    self.trained_classifier = row.get_classifier()
AttributeError: 'NoneType' object has no attribute 'get_classifier'

Where am I doing wrong?
Please help for my thesis
Thank you
