### ISSUE TITLE
NumPy, SciPy, NLTK

### ISSUE THREAD

**Issue by misskbar** [cyhex/streamcrab#19]
Hello, 

I wonder what role do these libraries in the project. 

That is, the classifiers are part of NumPy and SciPy or NLTK?

**Comment by cyhex** [comment]
classifiers are part of NLTK, NLTK depended on NumPy. 
SciPy - i am not sure.

**Comment by cyhex** [comment]
It looks like MaxEnt of NLTK uses SkiPy internally
