### ISSUE TITLE
Not sure what changes to make to twitterCollector.py

### ISSUE THREAD

**Issue by dwmcqueen** [cyhex/streamcrab#3]
What fields should be replaced?  I see username / password - is this Twitter username / password?  Anything else?

**Comment by cyhex** [comment]
i have made some changes to twitterCollector.py, take a look.

but the only thing that you have to change is the username/password for your twitter account.

**Comment by dwmcqueen** [comment]
How does it avoid using Oauth authentication?

**Comment by cyhex** [comment]
the stream api supports basic http auth....

**Comment by dwmcqueen** [comment]
Perfect.  Looked at the code and it makes sense.   Any tips on what to put in here:

```
""" List of keywords to track"""
trackingK = [':)']
```

I assume keywords that lead to positive tweets?

**Comment by cyhex** [comment]
yes, you can also use smiles as keywords. please remember that you have to have about the same size positive and negative tweets
db.

**Comment by dwmcqueen** [comment]
Thank you.  Comma delimited (sorry for all questions)?

On Wed, Oct 19, 2011 at 9:33 AM, cyhex <
reply@reply.github.com>wrote:

> yes, you can also use smiles as keywords. please remember that you have to
> have about the same size positive and negative tweets
> db.
> 
> dwmcqueen reply@reply.github.com wrote:
> 
> > Perfect.  Looked at the code and it makes sense.   Any tips on what to put
> > in here:
> > 
> >    """ List of keywords to track"""
> >    trackingK = [':)']
> > 
> > I assume keywords that lead to positive tweets?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/cyhex/smm/issues/3#issuecomment-2455283
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cyhex/smm/issues/3#issuecomment-2456451

## 

Duncan McQueen
OpenThinking Systems, LLC
http://www.openthinkingsystems.com

**Comment by cyhex** [comment]
you need to collect 2 different data sets (files) one for positive one for negative, take a look at collector / trainer / tweetClassifier.py that will give you a better understanding.
