### ISSUE TITLE
Incorrect stream for Twitter Stream API

### ISSUE THREAD

**Issue by dwmcqueen** [cyhex/streamcrab#5]
The collector/trainer/twitterCollector.py has this stream:

http://stream.twitter.com/1/statuses/filter.json

It should be this:

https://stream.twitter.com/1/statuses/filter.json

(notice the https)

**Comment by cyhex** [comment]
it used to work with http... possibly it has been changed... i dont really know.

**Comment by dwmcqueen** [comment]
I think it did just change recently.  I know I got timeouts with http, so I assume it is safe to make the change to https.  At least the Twitter docs say to use https.

**Comment by dwmcqueen** [comment]
If you look at the docs from Twitter - it says it is SSL only:

https://dev.twitter.com/docs/streaming-api

I'd recommend changing the code accordingly.

**Comment by dwmcqueen** [comment]
Can this one be reopened - still getting connection failures here if not using https?
