### ISSUE TITLE
Small issue on running python tests/moodClientServerTest.py

### ISSUE THREAD

**Issue by dwmcqueen** [cyhex/streamcrab#6]
The directions say basically to start in the tracker directory.  I get this error when doing that:

Traceback (most recent call last):
  File "tests/moodClientServerTest.py", line 4, in <module>
    from tracker.lib.moodClassifierClient import MoodClassifierTCPClient
ImportError: No module named tracker.lib.moodClassifierClient
dwmcqueen@dwmcqueen-VirtualBox:~/smm/tracker$

**Comment by dimaspriyanto** [comment]
What's the solution to fix this issue? I just tried and got this issue

**Comment by cyhex** [comment]
please make sure that you are outside tracker directory
